version: 2

models:
  - name: stg_carrefour_sales
    columns:
      - name: barcode
        tests:
          - not_null
          - unique # Optionnel selon vos données

  - name: aggregation
    description: "Comparaison du CA entre le local FR et le Groupe par catégorie"